# Generated by Django 4.2.7 on 2026-06-29 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("hotel_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "HOTELS",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "USERS",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.IntegerField(primary_key=True, serialize=False)),
                ("room_number", models.CharField(max_length=10)),
                ("room_type", models.CharField(max_length=50)),
                ("price_per_night", models.FloatField()),
                ("max_occupancy", models.IntegerField()),
                ("description", models.CharField(max_length=300)),
                ("status", models.CharField(max_length=50)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "ROOMS",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.IntegerField(primary_key=True, serialize=False)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("total", models.FloatField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.user",
                    ),
                ),
            ],
            options={
                "db_table": "BOOKINGS",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.IntegerField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField()),
                ("comment", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.user",
                    ),
                ),
            ],
            options={
                "db_table": "REVIEWS",
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("Hpicture_id", models.IntegerField(primary_key=True, serialize=False)),
                ("image_url", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=300)),
                (
                    "hotel",
                    models.ForeignKey(
                        db_column="hotel_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "PICTURES",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("payment_method", models.CharField(max_length=50)),
                ("payment_date", models.DateField()),
                ("amount", models.FloatField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.booking",
                    ),
                ),
            ],
            options={
                "db_table": "PAYMENTS",
            },
        ),
        migrations.CreateModel(
            name="RoomPicture",
            fields=[
                ("picture_id", models.IntegerField(primary_key=True, serialize=False)),
                ("picture_url", models.CharField(max_length=200)),
                ("number", models.IntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        db_column="room_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.room",
                    ),
                ),
            ],
            options={
                "db_table": "Room_pictures",
                "unique_together": {("picture_id", "room")},
            },
        ),
    ]
